apiVersion: apps/v1
kind: Deployment
metadata:
  name: deidentification-in-v1
  namespace: deidentification
spec:
  replicas: 3  # 원하는 파드 수
  selector:
    matchLabels:
      app: fastapi-app
  template:
    metadata:
      labels:
        app: fastapi-app
    spec:
      containers:
        - name: fastapi-container
          image: deid-fastapi:1.0  # 빌드한 Docker 이미지 이름과 태그
          ports:
            - containerPort: 10213  # FastAPI 애플리케이션이 사용하는 포트