apiVersion: v1
kind: Service
metadata:
  name: deidentification-in-v1
  namespace: deidentification
spec:
  selector:
    app: fastapi-app
  ports:
    - protocol: TCP
      targetPort: 10213  # FastAPI 애플리케이션 포트
  type: ClusterIP  # 혹은 필요한 서비스 유형